### PR TITLE
Add missing find_package

### PR DESCRIPTION
**Pull request by kledom**
Add missing find_package call

Signed-off-by: Dominik Kleiser <KleiserDominik@outlook.com>

### CODE REVIEW

**Comment by ravijo** [comment]
Hi @kledom 

Thank you very much for your suggestion. I am a bit concerned about `find_package(Threads REQUIRED)` right now. I will point my reasons below-

1. For newer versions, i.e., `CMake 3.9+`, the `find_package(Threads REQUIRED)` is not required.
1. For older versions, i.e., `CMake < 3.9`, the `find_package(Threads REQUIRED)` is required.

    The reference for the above two points can be found [here](https://cliutils.gitlab.io/modern-cmake/chapters/packages/OpenMP.html). 

1. In our [CMakeLists.txt](https://github.com/ravijo/ros_openpose/blob/master/CMakeLists.txt) , we are supporting `cmake_minimum_required(VERSION 2.8.3)`.
1. As per the webpage [here](https://cliutils.gitlab.io/modern-cmake/chapters/packages/OpenMP.html), we also need to set `target_link_libraries` while using `find_package(OpenMP)`.
1. A Github page [here](https://github.com/torbjoernk/openMP-Examples/blob/master/CMakeLists.txt) shows that `find_package(Threads REQUIRED)` is not required and set `CMAKE_CXX_FLAGS` as `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")` as we are doing.
1. Additionally, an answer given in [SO](https://stackoverflow.com/a/28792611) doesn't mention the need for using `find_package(Threads REQUIRED)`. 

Considering all the points mentioned above, what is your opinion? What do you think?

**Comment by kledom** [comment]
Thank you for looking into this.

I'm running on Ubuntu 18.04 with ROS Melodic and CMake 3.17.1.
Without

    find_package(Threads REQUIRED)

building fails with the error message

    /usr/bin/ld: cannot find -lThreads::Threads

I'm not sure when this line is needed or not.

**Comment by ravijo** [comment]
I am glad to see that you made a workaround quickly by adding `find_package(Threads REQUIRED)`

> I'm running on Ubuntu 18.04 with ROS Melodic and CMake 3.17.1.

For now, 

- I mark it _"help wanted"_ as we need to reproduce it on multiple machines to confirm. 
- I am keeping this task on my todo list. 

As always, feel free to add your comments/suggestions, please.

**Comment by kledom** [comment]
I'll close this request. I think the issue you created is the better place for this discussion.

**Comment by ravijo** [comment]
Hi @kledom 

I just wanted to give you an update on this issue. Please check [here](https://github.com/ravijo/ros_openpose/issues/12#issuecomment-626201871).

Thanks!

**Pull request closed without merging**
