### PR TITLE
Fixed Incompatibility due to OpenPose 1.6

### PR DESCRIPTION
**Pull request by xiangzhi**
Hi,

I integrated your suggestion in #10 and fixed all the changes introduced by OpenPose 1.6 (op::CheckBool & op::String). The package now compiles on my machine and as far as I can tell, is working for my Kinect 2 setup.

### CODE REVIEW

**Comment by ravijo** [comment]
Hi @xiangzhi 

Thank you so much for this valuable help. I see the addition of `OP_CV2OPCONSTMAT`, `op::CheckBool` and `op::String`. Great!

Thanks again for making it compatible with OpenPose 1.6.

At this point, I am a little worried, as the suggestions may not work with OpenPose 1.5.1. We can do the following two workarounds-

1. Create a tag (similar to OpenPose) for the older version, i.e., 1.5.1
2. Or use `#ifdef OPENPOSE_VERSON` directive. _I am not sure if this directive exists in OpenPose._

Knowing that the changes are very few, I would prefer `#ifdef OPENPOSE_VERSON` directive if it exists. Otherwise, creating a tag is easy!

Once again, thank you for your support. I am looking forward to hearing from you.

**Comment by xiangzhi** [comment]
Hi @ravijo 

Option (2) looked to be the better option. I modified the CMakeLists.txt to pass in the versions and added preprocessor guards for all my changes. I tested it on my machine and the fixes work, but I don't have a 1.5.1 version to test against.

**Comment by ravijo** [comment]
Hi @xiangzhi 

Thank you very much for the quick response. Please give me 1-2 days. I will compile with the older version and merge this pull request.

Thanks for the great help!

**Comment by ravijo** [comment]
Hi @xiangzhi 

I have verified the compilation of the following OpenPose versions-

- 1.5.1
- 1.6.0

The code compiles without any error.

I have merged the request. 

Furthermore, I have done two minor changes in the code mentioned below-

1. Fixed a small error in the code, which can be seen [here](https://github.com/xiangzhi/ros_openpose/blob/bb727a69687f5230bb8d6b20598717d1db0e4f38/src/rosOpenpose.cpp#L135).
1. Defined a macro for compatibility with older versions as shown below-
```
#define OPENPOSE1POINT6_OR_HIGHER OpenPose_VERSION_MAJOR >= 1 && OpenPose_VERSION_MINOR >= 6 
```

Thanks again for the help. I appreciate it!

**Comment by xiangzhi** [comment]
no problem! Thanks

**Pull request merged**
