### PR TITLE
Edit of README file

### PR DESCRIPTION
**Pull request by ruksen25**
Hereby the discussed edit of the README file. Feel free to pick and chose and add changes as you please. This is only supposed to be a help not an invasion :)

### CODE REVIEW

**Comment by ravijo** [comment]
This is fabulous. Looks all right. 

Below is a minor request:

We have 5 sections saying *"Steps to Run with..."*. I think we should make them subsections under *"Camera Run Instructions"* in the following way:

```
## Camera Run Instructions
<a name="rgbcam"></a>
### Steps to Run with any Color Camera such as Webcam etc.
```
As you can see, I declared a new section titled "Camera Run Instructions" and made "Steps to Run with..." as a subsection.

**Comment by ruksen25** [comment]
Yes, I was considering this as well, but was a bit uncertain about the usefulness of it as people usually jump to a specific camera instruction. That is why I made structure like that in the table of content but not in the document itself.  But it is probably nicer like that.  I will add these changes.

**Comment by ravijo** [comment]
yes, please!

**Comment by ruksen25** [comment]
Should I write something in the camera section before the different instructions? I was considering typing something like:
In this section you will find the instructions for running ros_openpose with one of the following cameras: Color camera, Realsense, Kinect v2, Azure Kinect, ZED2. 
If you have a different camera and would like to use ros_openpose with depth properties, you might be able to do so by creating your own Config_<camera_name>.launch file based on one of the existing ones and modify it to suit your specific camera. Remember that what ever you chose as the camera_name should be used as an argument when launching the run.launch . To achieve visualisations you  also need to create new modified versions of the rviz scripts only_person_<camera_name>.rviz and  person_pointcloud_<camera_name>.rviz . 


If you successfully create modified files and run ros_openpose with a depth camera that is not mentioned here, please share your files and necessary steps for running with your camera  so that it can be available to others. 





Let me know if you think this is a bad idea. I myself was thinking that it might give people the impression that you/we open up for more intricate support in the process of modifying said files, which could become a burden...

**Comment by ravijo** [comment]
> Should I write something in the camera section before the different instructions? I was considering typing something like:
> In this section you will find the instructions for running ros_openpose with one of the following cameras: Color camera, Realsense, Kinect v2, Azure Kinect, ZED2.
> If you have a different camera and would like to use ros_openpose with depth properties, you might be able to do so by creating your own Config_<camera_name>.launch file based on one of the existing ones and modify it to suit your specific camera. Remember that what ever you chose as the camera_name should be used as an argument when launching the run.launch . To achieve visualisations you also need to create new modified versions of the rviz scripts only_person_<camera_name>.rviz and person_pointcloud_<camera_name>.rviz .

This is helpful. We can add this info. We have some info. in faq#1. We should provide a hyperlink to faq#1 or simplify somehow?

> If you successfully create modified files and run ros_openpose with a depth camera that is not mentioned here, please share your files and necessary steps for running with your camera so that it can be available to others.
> 
> Let me know if you think this is a bad idea. I myself was thinking that it might give people the impression that you/we open up for more intricate support in the process of modifying said files, which could become a burden...

As you said, this feels like tech support from us. We don't do that.

BTW, I saw your latest changes, and they look impressive. Let me know when I can merge them.

**Comment by ruksen25** [comment]
I will puzzle a bit with where we provide what info regarding adapting to a new camera and then make a new commit. 
Perhaps you can wait with the merge until this is sorted out. I will let you know. 


It was actually mostly the first part that I thought people might misinterpret as opening up for providing support for the process of adapting the wrapper for other cams. 

The last part i just about making newly created compatibilities available to others just like we did with my files that I sent to you, and you added back then. I was just meant that part as an encouragement for contribution, but if you interpreted it differently maybe I should rephrase or leave it out entirely. 

My last changes were not any thing extraordinary I think :) but I am glad that you appreciate my effort.

**Comment by ravijo** [comment]
Done :+1:

**Comment by ruksen25** [comment]
I guess you misunderstood 😊 but I can just make a new pull request once I have adapted the info on adding a new cam.

**Comment by ravijo** [comment]
I was traveling and couldn't pay attention to the message. My apologies.

I think it is a good idea to enumerate the name of every contributor on the documentation page. I hope you agree!

So far, the documentation is looking much better than before. However, I am waiting for your new merge request in the future.

Thanks a lot.

**Pull request merged**
